Repository 7-lin/Final_Project_FE, pull requests merged in 2023-03, with the labels that each got.

#8 Design: 헤더, 푸터, 메인페이지 일부 UI 마크업
  package-lock.json
  package.json
  public/banner0.png
  public/banner1.png
  public/banner2.png
  public/banner3.png
  public/category-all.png
  public/category-fam.png
  public/category-m.png
  public/category-senior.png
  public/category-w.png
  public/logo_g.png
  public/logo_shiny.png
  public/logo_text.png
  src/commons/Footer.tsx
  src/commons/Header.tsx
  src/global/globalStyles.ts
  src/pages/main/BannerSlider.tsx
  src/pages/main/GroupCategory.tsx
  src/pages/main/MainPage.tsx
Labels: ✨ style

#9 Update package-lock.json
  package-lock.json
Labels: 💉 fix

#11 Fix: 머지컨플릭트 해결
  package-lock.json
  public/test.png
  src/commons/Header.tsx
  src/pages/main/GroupCategory.tsx
  src/pages/main/MainPage.tsx
Labels: 💉 fix

#13 Fix: 빌드 코드 추가
  package-lock.json
  src/pages/main/MainPage.tsx
Labels: 💉 fix

#14 feat: 그룹별 페이지 마크업 작업
  package.json
  src/pages/groups/Groups.tsx
  src/routes/router.tsx
Labels: ✨ style

#18 design: 그룹별 페이지 모바일버전 마크업 작업
  src/pages/groups/Groups.tsx
Labels: ✨ style

#19 Feature/hyeonju
  public/face.png
  public/floating.png
  public/footer-blog.png
  public/footer-facebook.png
  public/footer-insta.png
  public/footer-link.png
  public/footer-youtube.png
  public/logo_go.png
  public/test.png
  src/App.tsx
  src/commons/FloatingIcon.tsx
  src/commons/Footer.tsx
  src/global/globalStyles.ts
  src/pages/main/GroupCategory.tsx
Labels: ✨ style

#21 Design: 로그인 페이지 모달창 마크업
  src/commons/Button.tsx
  src/commons/Input.tsx
  src/commons/Modal.tsx
  src/global/globalStyles.ts
  src/hooks/useModal.tsx
  src/main.tsx
  src/pages/login/Login.tsx
  src/pages/login/modal_content/FindIdPasswordModal.tsx
  src/pages/login/modal_content/NonMemberResvationModal.tsx
  src/pages/login/modal_content/ShowIdModal.tsx
  src/pages/login/modal_content/ShowPwModal.tsx
  src/pages/signup/Signup.tsx
  src/routes/router.tsx
  src/store/atom.ts
  src/store/modalAtom.ts
  src/utils/scroll.ts
Labels: ✨ style, 🌟 feature

#26 Design: 플로팅 모달 추가
  package-lock.json
  package.json
  src/commons/FloatingIcon.tsx
  src/commons/FloatingInput.tsx
  src/commons/FloatingModal.tsx
  src/commons/Terms.tsx
  src/global/globalStyles.ts
  src/pages/main/MainPage.tsx
  src/utils/CurrentTime.tsx
Labels: ✨ style

#30 Design: 회원가입 페이지 마크업
  public/select_arrow_down.svg
  public/senior_1920.png
  src/commons/Button.tsx
  src/commons/Input.tsx
  src/commons/Modal.tsx
  src/commons/Select.tsx
  src/pages/login/Login.tsx
  src/pages/login/modal_content/FindIdPasswordModal.tsx
  src/pages/signup/Signup.tsx
  src/pages/signup/SignupSite.tsx
  src/pages/signup/SignupType.tsx
  src/routes/router.tsx
Labels: ✨ style

#31 Design: 후기 수정, 삭제 모달 추가
  src/commons/ReviewModal.tsx
  src/pages/review-detail/Comments.tsx
  src/pages/review-detail/ReviewDetail.tsx
Labels: ✨ style

#32 Design: 여행 유형 테스트 페이지 UI 구성
  public/circle-insta.png
  public/circle-kakao.png
  public/circle-sharelink.png
  public/circle-youtube.png
  public/face.png
  public/logo_go.png
  public/number1.png
  public/number2.png
  public/number3.png
  public/number4.png
  public/number5.png
  public/result-cultrue.png
  public/result-golf.png
  public/result-ocean.png
  public/result-trekking.png
  public/result-volunteer.png
  public/trip-test1.png
  public/trip-test2.png
  public/trip-test3.png
  public/trip-test4.png
  public/trip-test5.png
  src/commons/FloatingInput.tsx
  src/global/globalStyles.ts
  src/pages/main/MainPage.tsx
  src/pages/trip-test/TestResult.tsx
  src/pages/trip-test/TripTest.tsx
  src/routes/router.tsx
Labels: ✨ style

#34 Feature/jaeheon
  package-lock.json
  package.json
  src/commons/Button.tsx
  src/commons/Input.tsx
  src/commons/Modal.tsx
  src/commons/Select.tsx
  src/global/globalStyles.ts
  src/pages/login/Login.tsx
  src/pages/login/modal_content/FindIdPasswordModal.tsx
  src/pages/login/modal_content/ShowIdModal.tsx
  src/pages/login/modal_content/ShowPwModal.tsx
  src/pages/signup/SignupSite.tsx
  src/pages/signup/SignupType.tsx
Labels: ✨ style, 🌟 feature

#35 Design: 모바일버전 메인페이지 구성
  src/commons/FloatingIcon.tsx
  src/commons/Footer.tsx
  src/commons/Header.tsx
  src/global/globalStyles.ts
  src/pages/login/Login.tsx
  src/pages/main/GroupCategory.tsx
  src/pages/main/MainPage.tsx
Labels: ✨ style

#36 Feature/hyeonju
  public/airplane.png
  public/playbutton.png
  src/commons/FloatingIcon.tsx
  src/commons/FloatingInput.tsx
  src/commons/FloatingModal.tsx
  src/commons/Footer.tsx
  src/commons/Header.tsx
  src/global/globalStyles.ts
  src/pages/main/GroupCategory.tsx
  src/pages/main/MainPage.tsx
Labels: ✨ style

#37 Feat: 로그인 페이지 + 관련 모달창 react-hook-form 연결
  src/@types/data.d.ts
  src/commons/Modal.tsx
  src/pages/login/Login.tsx
  src/pages/login/modal_content/FindIdPasswordModal.tsx
  src/pages/login/modal_content/NonMemberResvationModal.tsx
  src/pages/signup/SignupSite.tsx
Labels: ✨ style, 🌟 feature

#40 design: 공지사항 페이지 마크업 작업
  index.html
  package-lock.json
  package.json
  src/pages/notice/Data.tsx
  src/pages/notice/Information.tsx
  src/pages/notice/Notice.tsx
  src/pages/notice/Way.tsx
  src/routes/router.tsx
Labels: ✨ style, 🌟 feature

#43 Design: 모바일버전 예약결제페이지 UI 구성
  src/commons/FloatingInput.tsx
  src/commons/FloatingModal.tsx
  src/commons/Footer.tsx
  src/commons/Header.tsx
  src/pages/reservation/PaymentModal.tsx
  src/pages/reservation/Reservation.tsx
  src/pages/trip-test/TripTest.tsx
  src/routes/router.tsx
Labels: ✨ style, 🌟 feature
