Repository 7-lin/Final_Project_FE, pull requests merged in 2023-04, with the labels that each got.

#44 Design: 글로벌스타일 모바일버전 main에 패딩 20px 추가
  src/commons/Footer.tsx
  src/commons/Header.tsx
  src/global/globalStyles.ts
  src/pages/main/MainPage.tsx
  src/pages/reservation/Reservation.tsx
Labels: ✨ style

#45 Desigin: 마이페이지 마크업 작업
  public/default_profile.png
  src/@types/data.d.ts
  src/pages/login/Login.tsx
  src/pages/login/modal_content/FindIdPasswordModal.tsx
  src/pages/login/modal_content/NonMemberResvationModal.tsx
  src/pages/login/modal_content/ShowIdModal.tsx
  src/pages/mypage/Favor.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/MyReservation.tsx
  src/pages/mypage/Point.tsx
  src/pages/mypage/components/ChangeInfoModal.tsx
  src/pages/mypage/components/ProductCard.tsx
  src/pages/mypage/components/SideBar.tsx
  src/pages/mypage/components/UserInfo.tsx
  src/pages/mypage/components/WithdrawlModal.tsx
  src/pages/signup/SignupSite.tsx
  src/routes/router.tsx
Labels: ✨ style, 🌟 feature

#46 Design: pc버전 예약/결제페이지 구성
  src/commons/Modal.tsx
  src/commons/Terms.tsx
  src/pages/main/MainPage.tsx
  src/pages/reservation/PaymentModal.tsx
  src/pages/reservation/Reservation.tsx
Labels: ✨ style

#51 Feat: 회원가입, 로그인 api 연결 (로그인 미완성)
  package-lock.json
  package.json
  src/@types/data.d.ts
  src/apis/auth.ts
  src/apis/instance.ts
  src/commons/Header.tsx
  src/pages/login/Login.tsx
  src/pages/signup/SignupSite.tsx
  src/store/loginAtom.ts
  src/store/userInfoAtom.ts
  src/utils/cookie.ts
  src/utils/localStorage.ts
Labels: 🌟 feature

#55 Feat: private route 설정
  src/commons/Header.tsx
  src/pages/login/Login.tsx
  src/routes/PrivateRoute.tsx
  src/routes/router.tsx
Labels: 🌟 feature

#61 design: 그룹별 페이지 UI 수정
  src/pages/groups/Filter.tsx
  src/pages/groups/Groups.tsx
  src/pages/groups/Product.tsx
  src/pages/groups/SubMenu.tsx
  src/pages/search/Search.tsx
  src/routes/router.tsx
Labels: ✨ style

#62 design: 상세페이지 마크업 완료
  public/product_detail_1.jpg
  public/product_detail_2.jpg
  public/product_detail_3.jpg
  public/product_detail_4.jpg
  public/product_detail_5.jpg
  public/product_detail_6.png
  public/product_detail_7.png
  public/product_detail_icon_1.svg
  public/product_detail_icon_2.svg
  public/product_detail_icon_3.svg
  public/product_detail_icon_4.svg
  public/product_detail_icon_5.svg
  public/product_detail_icon_6.svg
  src/@types/data.d.ts
  src/@types/props.d.ts
  src/commons/Breadcrumb.tsx
  src/commons/Modal.tsx
  src/commons/ReviewModal.tsx
  src/pages/groups/Groups.tsx
  src/pages/groups/Product.tsx
  src/pages/product-detail/ProductDetail.tsx
  src/pages/product-detail/ProductDetailModal.tsx
  src/pages/product-detail/ProductDetailModalOption.tsx
  src/pages/review-detail/MainContents.tsx
  src/pages/review-detail/RecommendSlider.tsx
  src/pages/review-detail/ReviewDetail.tsx
  src/pages/review-write/ReviewWrite.tsx
  src/pages/review/Review.tsx
  src/pages/review/ReviewFilterItem.tsx
  src/pages/review/ReviewFilters.tsx
  src/routes/router.tsx
Labels: ✨ style

#63 Design: 여행추천페이지 UI 구성 완료
  public/background-cultrue.png
  public/background-golf.png
  public/background-ocean.png
  public/background-trekking.png
  src/apis/request.ts
  src/commons/FloatingIcon.tsx
  src/commons/Modal.tsx
  src/pages/groups/Product.tsx
  src/pages/recommend/RecommendPage.tsx
  src/pages/recommend/TestResult.tsx
  src/pages/reservation/ReservationPage.tsx
  src/routes/router.tsx
Labels: ✨ style

#65 Feat: 아이디/비번 찾기 api 연결(백엔드 api 이슈로 동작 x), refresh token 로직 추가
  src/apis/auth.ts
  src/apis/instance.ts
  src/commons/Header.tsx
  src/pages/login/Login.tsx
  src/pages/login/modal_content/FindIdPasswordModal.tsx
  src/pages/login/modal_content/ShowIdModal.tsx
  src/pages/login/modal_content/ShowPwModal.tsx
  src/pages/mypage/components/UserInfo.tsx
  src/pages/mypage/components/WithdrawlModal.tsx
  src/utils/cookie.ts
Labels: 🌟 feature

#66 Feat: 테스트결과 로컬스토리지 저장, 여행추천페이지 적용
  public/background-culture.png
  public/notfound.png
  src/pages/not-found/NotFoundPage.tsx
  src/pages/recommend/RecommendPage.tsx
  src/pages/recommend/TestResult.tsx
  src/routes/router.tsx
Labels: ✨ style, 🌟 feature

#68 Feat: 카카오 소셜 로그인 인증코드 받아오기 실험
  src/pages/kakaologin/KakaoLogin.tsx
  src/pages/login/Login.tsx
  src/pages/login/components/GoogleBtn.tsx
  src/pages/login/components/KakaoBtn.tsx
  src/pages/login/components/NaverBtn.tsx
  src/routes/router.tsx
Labels: 🌟 feature

#72 feature: 그룹별 페이지 상품 api 연결
  src/@types/data.d.ts
  src/apis/request.ts
  src/pages/groups/Filter.tsx
  src/pages/groups/Groups.tsx
  src/pages/groups/Product.tsx
  src/pages/recommend/RecommendPage.tsx
Labels: 🌟 feature

#73 Feat: 챗봇 atom 생성
  src/App.tsx
  src/commons/Chatbot/FloatingIcon.tsx
  src/commons/Chatbot/FloatingInput.tsx
  src/commons/Chatbot/FloatingModal.tsx
  src/commons/Chatbot/questionsAndAnswers.ts
  src/commons/FloatingModal.tsx
  src/commons/Terms.tsx
  src/pages/recommend/RecommendPage.tsx
  src/pages/recommend/TestResult.tsx
  src/pages/recommend/TripTestPage.tsx
  src/pages/reservation/EditUserInfoModal.tsx
  src/pages/reservation/ReservationPage.tsx
  src/store/chatbotAtom.ts
Labels: ✨ style, 🌟 feature, 🛠 refactor

#76 Feat: 회원 정보 수정, 회원 탈퇴, api 추가
  package-lock.json
  package.json
  src/@types/data.d.ts
  src/apis/auth.ts
  src/apis/instance.ts
  src/commons/Header.tsx
  src/commons/Terms.tsx
  src/pages/login/Login.tsx
  src/pages/mypage/components/ChangeInfoModal.tsx
  src/pages/mypage/components/WithdrawlModal.tsx
  src/pages/signup/SignupSite.tsx
  src/pages/signup/SignupType.tsx
  src/pages/sociallogin/GoogleLogin.tsx
  src/pages/sociallogin/KakaoLogin.tsx
  src/pages/sociallogin/NaverLogin.tsx
  src/routes/PrivateRoute.tsx
  src/store/userInfoAtom.ts
Labels: 🌟 feature

#77 Feat: 챗봇 상태관리 로직 수정
  public/me.png
  src/@types/data.d.ts
  src/commons/Chatbot/ChatList.tsx
  src/commons/Chatbot/FloatingInput.tsx
  src/commons/Chatbot/FloatingModal.tsx
  src/commons/Chatbot/questionsAndAnswers.ts
  src/pages/recommend/ResultPack.ts
  src/pages/recommend/TestResult.tsx
  src/pages/recommend/TripTestPage.tsx
  src/store/chatbotAtom.ts
Labels: 🌟 feature

#80 Design: 상세, 후기, 장바구니 마크업 완료
  public/cart_cheack_icon.svg
  public/input_error_icon.svg
  public/review_write_icon.svg
  src/@types/props.d.ts
  src/commons/Header.tsx
  src/commons/Modal.tsx
  src/commons/ModalProductCard.tsx
  src/commons/ProductInfosCard.tsx
  src/commons/ReviewModal.tsx
  src/global/globalStyles.ts
  src/pages/cart/Cart.tsx
  src/pages/product-detail/ProductDetail.tsx
  src/pages/product-detail/ProductDetailModal.tsx
  src/pages/product-detail/ProductDetailModalOption.tsx
  src/pages/product-detail/ProductDetailReviews.tsx
  src/pages/review-detail/Comments.tsx
  src/pages/review-detail/MainContents.tsx
  src/pages/review-detail/RecommendSlider.tsx
  src/pages/review-detail/ReviewDetail.tsx
  src/pages/review-write/ReviewWrite.tsx
  src/pages/review/Review.tsx
  src/pages/review/ReviewFilterItem.tsx
  src/pages/review/ReviewItems.tsx
  src/pages/review/ReviewModal.tsx
  src/routes/router.tsx
  src/utils/useDragScroll.tsx
Labels: ✨ style

#81 Feat: 마이 페이지 회원 정보 수정에서 전화번호 수정 시 중복 검사 추가
  src/@types/data.d.ts
  src/apis/auth.ts
  src/apis/instance.ts
  src/main.tsx
  src/pages/login/modal_content/FindIdPasswordModal.tsx
  src/pages/mypage/components/ChangeInfoModal.tsx
  src/pages/mypage/components/UserInfo.tsx
  src/pages/signup/SignupSite.tsx
  src/routes/PrivateRoute.tsx
Labels: ✨ style, 🌟 feature

#82 Feat: 챗봇 기록 저장기능 완성
  public/floating.png
  src/commons/Chatbot/ChatList.tsx
  src/commons/Chatbot/FloatingInput.tsx
  src/commons/Chatbot/FloatingModal.tsx
  src/commons/Chatbot/questionsAndAnswers.ts
  src/store/chatbotAtom.ts
Labels: ✨ style, 🌟 feature

#83 Feat: 로그아웃, 비회원 예약 조회, 회원 예약 조회, 예약 취소, 예약 상세 보기, 다시 예약하기
  src/@types/data.d.ts
  src/apis/auth.ts
  src/apis/instance.ts
  src/commons/Header.tsx
  src/main.tsx
  src/pages/groups/Groups.tsx
  src/pages/login/Login.tsx
  src/pages/login/modal_content/NonMemberResvationModal.tsx
  src/pages/mypage/Favor.tsx
  src/pages/mypage/MyReservation.tsx
  src/pages/mypage/components/ReservationDetailModal.tsx
  src/pages/mypage/components/ReservationProductCard.tsx
  src/pages/mypage/components/WishListProductCard.tsx
  src/pages/mypage/components/WithdrawlModal.tsx
Labels: ✨ style, 🌟 feature

#84 Feat: 마이페이지 위시리스트 조회, 삭제, 전체 삭제, 상세 페이지 이동
  src/@types/data.d.ts
  src/apis/auth.ts
  src/hooks/useWishlistQuery.ts
  src/pages/mypage/Favor.tsx
  src/pages/mypage/components/WishListProductCard.tsx
Labels: 🌟 feature

#86 Feat: 상세페이지 api 호출 완료, 예약 페이지 정보 전달 완료
  public/product_detail_7.png
  src/@types/data.d.ts
  src/@types/enum.d.ts
  src/@types/props.d.ts
  src/apis/request.ts
  src/pages/cart/Cart.tsx
  src/pages/product-detail/ProductDetail.tsx
  src/pages/product-detail/ProductDetailModal.tsx
  src/pages/product-detail/ProductDetailModalOption.tsx
  src/pages/product-detail/ProductDetailModalOptionCard.tsx
  src/pages/product-detail/ProductDetailReviews.tsx
  src/pages/reservation/ReservationPage.tsx
  src/pages/review-write/ReviewWrite.tsx
Labels: 🌟 feature

#87 feat: 그룹별 페이지 api 연결(필터 제외)
  src/@types/data.d.ts
  src/apis/request.ts
  src/pages/groups/Filter.tsx
  src/pages/groups/Groups.tsx
  src/pages/groups/Product.tsx
  src/pages/groups/Sort.tsx
  src/pages/groups/SubMenu.tsx
  src/pages/recommend/RecommendPage.tsx
  src/store/categoryAtom.ts
  src/utils/category.ts
  src/utils/sort.ts
Labels: 🌟 feature

#88 Feat: 챗봇 기능 완성
  public/banner-product-unknown.png
  public/banner-product.png
  public/banner-product10.png
  public/banner-product12.png
  public/banner-product6.png
  public/banner-product8.png
  src/commons/Chatbot/ChatList.tsx
  src/commons/Chatbot/FloatingInput.tsx
  src/commons/Chatbot/FloatingModal.tsx
  src/global/globalStyles.ts
  src/pages/main/BannerSlider.tsx
  src/store/chatbotAtom.ts
Labels: 🌟 feature

#90 feat: 장바구니 페이지 기능구현 중간제출, 예약 페이지에 전달하는 상품 정보 구조 수정
  src/@types/data.d.ts
  src/pages/cart/Cart.tsx
  src/pages/cart/MobileCart.tsx
  src/pages/product-detail/ProductDetailModal.tsx
Labels: 🌟 feature

#92 Feat: 회원가입 후 바로 로그인 처리, 회원정보 조회 커스텀 훅 생성
  src/@types/data.d.ts
  src/apis/auth.ts
  src/apis/instance.ts
  src/hooks/useUserInfoQuery.ts
  src/pages/login/Login.tsx
  src/pages/mypage/Favor.tsx
  src/pages/mypage/MyReservation.tsx
  src/pages/mypage/components/ChangeInfoModal.tsx
  src/pages/mypage/components/WithdrawlModal.tsx
  src/pages/signup/SignupSite.tsx
  src/store/userInfoAtom.ts
Labels: 🌟 feature

#94 Feat: 상세페이지 찜 추가 및 삭제 api 연결
  src/hooks/useAddWishlistMutation.ts
  src/hooks/useDeleteWishlistMutation.ts
  src/pages/mypage/components/WishListProductCard.tsx
  src/pages/product-detail/ProductDetail.tsx
Labels: 🌟 feature

#96 Feat: 상품 카드 하트를 활용한 찜 추가 및 삭제 완료, 경로 바뀔때 마다 화면 최상단으로 이동
  src/App.tsx
  src/pages/groups/Product.tsx
Labels: ✨ style, 🌟 feature

#98 feat: 그룹별 페이지 api 연결
  src/@types/data.d.ts
  src/apis/request.ts
  src/pages/groups/Filter.tsx
  src/pages/groups/Groups.tsx
  src/pages/groups/Sort.tsx
  src/pages/groups/SubMenu.tsx
  src/store/categoryAtom.ts
  src/utils/filter.ts
Labels: 🌟 feature

#100 Feat: 장바구니 기능 구현 완료
  src/@types/data.d.ts
  src/@types/props.d.ts
  src/pages/cart/Cart.tsx
  src/pages/product-detail/ProductDetailModal.tsx
  src/pages/product-detail/ProductDetailModalOption.tsx
Labels: 🌟 feature

#101 Feat: 회원/비회원 예약기능 완성
  src/@types/data.d.ts
  src/apis/request.ts
  src/commons/Header.tsx
  src/pages/main/BannerSlider.tsx
  src/pages/recommend/RecommendPage.tsx
  src/pages/recommend/TestResult.tsx
  src/pages/reservation/EditUserInfoModal.tsx
  src/pages/reservation/PaymentModal.tsx
  src/pages/reservation/ReservationPage.tsx
  src/pages/signup/SignupSite.tsx
Labels: 🌟 feature

#103 Feat: 검색 페이지 최소한의 구현
  src/@types/data.d.ts
  src/apis/auth.ts
  src/apis/instance.ts
  src/apis/request.ts
  src/commons/Chatbot/FloatingInput.tsx
  src/commons/Header.tsx
  src/pages/cart/Cart.tsx
  src/pages/groups/Groups.tsx
  src/pages/groups/Product.tsx
  src/pages/login/Login.tsx
  src/pages/login/modal_content/FindIdPasswordModal.tsx
  src/pages/login/modal_content/NonMemberResvationModal.tsx
  src/pages/mypage/Favor.tsx
  src/pages/mypage/MyReservation.tsx
  src/pages/mypage/components/ChangeInfoModal.tsx
  src/pages/mypage/components/ReservationDetailModal.tsx
  src/pages/mypage/components/ReservationProductCard.tsx
  src/pages/product-detail/ProductDetail.tsx
  src/pages/product-detail/ProductDetailModal.tsx
  src/pages/reservation/EditUserInfoModal.tsx
  src/pages/review-write/ReviewWrite.tsx
  src/pages/search/Search.tsx
  src/pages/signup/SignupSite.tsx
Labels: ✨ style, 🌟 feature

#105 feat: 테마별 페이지, 지역별 페이지 생성
  src/commons/Header.tsx
  src/pages/category/Category.tsx
  src/pages/category/Destination.tsx
  src/pages/category/Filter.tsx
  src/pages/category/Groups.tsx
  src/pages/category/Product.tsx
  src/pages/category/Sort.tsx
  src/pages/category/Themes.tsx
  src/pages/recommend/RecommendPage.tsx
  src/pages/search/Search.tsx
  src/routes/router.tsx
Labels: 🌟 feature

#108 Fix: 상품추천페이지 에러 해결
  src/@types/data.d.ts
  src/commons/Chatbot/FloatingInput.tsx
  src/commons/Header.tsx
  src/pages/login/Login.tsx
  src/pages/main/GroupCategory.tsx
  src/pages/recommend/RecommendPage.tsx
  src/pages/reservation/PaymentModal.tsx
  src/pages/reservation/ReservationPage.tsx
  src/pages/signup/SignupType.tsx
  src/routes/router.tsx
Labels: 🌟 feature, 💉 fix

#110 Fix: 에러코드 주석처리
  src/pages/reservation/PaymentModal.tsx
  src/pages/reservation/ReservationPage.tsx
Labels: 💉 fix

#111 Fix: 주문번호 안 뜨는 오류 해결
  src/commons/Header.tsx
  src/pages/mypage/components/ReservationProductCard.tsx
  src/pages/recommend/RecommendPage.tsx
  src/pages/recommend/TripTestPage.tsx
  src/pages/reservation/EditUserInfoModal.tsx
  src/pages/reservation/PaymentModal.tsx
  src/pages/reservation/ReservationPage.tsx
  src/store/categoryAtom.ts
Labels: 💉 fix

#112 Feature/jaeheon
  public/spinner.svg
  src/apis/instance.ts
  src/hooks/useAddWishlistMutation.ts
  src/hooks/useDeleteWishlistMutation.ts
  src/hooks/useWishlistQuery.ts
  src/pages/category/Product.tsx
  src/pages/mypage/Favor.tsx
  src/pages/mypage/MyReservation.tsx
  src/pages/mypage/components/WishListProductCard.tsx
  src/pages/product-detail/ProductDetail.tsx
  src/pages/search/Search.tsx
Labels: ✨ style, 🌟 feature, 🛠 refactor

#117 Feat: 서치바 컴포넌트화
  src/commons/Header.tsx
  src/commons/SearchBar.tsx
  src/pages/main/MainPage.tsx
Labels: 🌟 feature, 🛠 refactor
